// @flow
export const OPEN_DRAWER = 'OPEN_DRAWER'
export const CLOSE_DRAWER = 'CLOSE_DRAWER'
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER'
export const OPEN_USER_MENU = 'OPEN_USER_MENU'
export const CLOSE_USER_MENU = 'CLOSE_USER_MENU'
export const TOGGLE_USER_MENU = 'TOGGLE_USER_MENU'
